[#175] Admin access for rate plans
apigee/apigee-m10n-drupal pull request #182
Opened 2019-07-24 09:28 UTC by arshad

Fixes #175

2019-07-25 18:10 UTC, arlina-espinoza requested changes
While this PR will effectively block the purchase of a purchase the rate plan to an admin that is not the assigned developer, it will also give and access denied when an admin is trying to view/purchase a plan for someone else. Example:
- Rate plan "AC Plan 2" is assigned to a developer "dev-user", with drupal uid 3.
- As a drupal admin (uid: 2):
  - Tries to purchase the plan for itself (/user/2/monetization/product-bundle/{product_bundle}/plan/{rate_plan}: gets access denied - _OK_ because uid 2 is not the assigned developer and should not be able to purchase the plan.
  - Tries to purchase the plan for the assigned developer (/user/3/monetization/product-bundle/{product_bundle}/plan/{rate_plan}: PR returns access denied, but it should be allowed as uid 3 is the assigned developer.

It looks like it's not so much of an issue of access control - an admin with the `"$operation rate_plan as anyone"` permission should be able to access all of the plans-. Perhaps we can approach this by filtering out the plans that can effectively  be purchased by each user on it's `/user/{user}/plans` page?

2019-07-25 18:10 UTC, arlina-espinoza commented on src/Entity/Access/RatePlanAccessControlHandler.php
> +    if ($rate_plan instanceof StandardRatePlanInterface && $account->hasPermission("$operation rate_plan as anyone")) {
I don't think this is correct, as it would only allow admins to do operations on behalf of someone else on standard rate plans.

2019-08-05 08:30 UTC, arshad commented on src/Entity/Access/RatePlanAccessControlHandler.php
> +    if ($rate_plan instanceof StandardRatePlanInterface && $account->hasPermission("$operation rate_plan as anyone")) {
@arlina-espinoza is this taken care of in https://github.com/apigee/apigee-m10n-drupal/pull/185?

2019-08-05 22:02 UTC, arlina-espinoza commented on src/Entity/Access/RatePlanAccessControlHandler.php
> +    if ($rate_plan instanceof StandardRatePlanInterface && $account->hasPermission("$operation rate_plan as anyone")) {
@arshad Yes, it would be#185 instead of this PR.

2019-08-26 17:34 UTC, arshad commented
@arlina-espinoza I believe this can be closed now?

2019-08-26 17:35 UTC, closed without merging